services:
  abalone-env:
    image: alexhaddon/abalone_analysis:latest
    container_name: abalone_analysis
    platform: linux/amd64
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/abalone_analysis     # Mount everything...
    environment:
      PASSWORD: "password"
      DISABLE_AUTH: true
